backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://cocky-varahamihira-ca0a52.netlify.com/

collections:
  - name: "articles"
    label: "Articles"
    description: "Article content, dates and author information."
    folder: "src/pages/articles"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "article" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {label: "Author", name: "author", widget: "relation", collection: "staffs", searchFields: ["firstName"], valueField: "firstName", displayFields: ["firstName","lastName"], required: true}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: 'Categories'
    name: 'categories'
    folder: "src/pages/categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    identifier_field: title
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string, required: false}
  - label: 'Staffs'
    name: 'staffs'
    folder: "src/pages/staffs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    identifier_field: lastName
    fields:
      - { label: Last name, name: lastName, required: true, widget: string }
      - { label: First name, name: firstName, required: true, widget: string }
      - {label: Description, name: description, widget: string, required: false}
      - {label: Profile URL, name: profileUrl, widget: string, required: false}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Image Gallery",
              name: "gallery",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Developer Groups", name: "developerGroups", widget: "markdown" }
          - {
              label: "Article Organizers",
              name: "organizers",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Images",
                    name: "gallery",
                    widget: "list",
                    fields:
                      [
                        { label: "Name", name: "name", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" },
                      ],
                  },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - {
              label: "Header Image",
              name: "headerImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Latest Article Heading", name: "latestArticleHeading", widget: "string" }
          - { label: "No Latest Article Text", name: "noLatestArticleText", hint: "This text will be displayed when there are no upcoming articles", required: true, widget: "string" }
          - { label: "Maps Note", name: "mapsNote", required: true, widget: "string" }
          - {
              label: "Call to Actions",
              name: "callToActions",
              required: true,
              widget: "object",
              fields:
                [
                  {
                    label: "First CTA",
                    name: "firstCTA",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {
                          label: "Link Type",
                          name: "linkType",
                          widget: "select",
                          options: ["internal", "external"],
                        },
                        {
                          label: "Link URL",
                          name: "linkURL",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                        }
                      ]
                  },
                  {
                    label: "Second CTA",
                    name: "secondCTA",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: "string" },
                        { label: "Sub Heading", name: "subHeading", widget: "string" },
                        {
                          label: "Link Type",
                          name: "linkType",
                          widget: "select",
                          options: ["internal", "external"],
                        },
                        {
                          label: "Link URL",
                          name: "linkURL",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                        }
                      ]
                  }
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "menubarAndFooter"
    label: "Menubar & Footer"
    files:
      - file: "src/pages/menubar/index.md"
        label: "Menubar"
        name: "menubar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "menubar" }
          - { label: "Menu title", name: "menuTitle", widget: "string", default: "Dallow legal" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                  {
                    label: Sub Items,
                    name: subItems,
                    widget: list,
                    fields:
                      [
                        { label: "Label", name: "label", widget: "string" },
                        { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                        { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                      ],
                  }
                ],
            }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }